Neos:
    Neos:
        userInterface:
            translation:
                autoInclude:
                    'Breadlesscode.Commentable':
                    - 'NodeTypes/Collection/*'
                    - 'NodeTypes/Content/*'
                    - 'NodeTypes/Mixin/*'
        fusion:
            autoInclude:
                Breadlesscode.Commentable: true
